-- ============================================================
-- 005_faqs_pgvector.sql — FAQ knowledge base + pgvector for RAG.
--
-- The admin manages a list of FAQs in /admin/faqs. The bot's
-- AskAboutRoomIntentHandler does a vector-search lookup against this table
-- before forwarding a user question to admin. Embeddings are 768-dim,
-- generated by Gemini text-embedding-004 and stored in the `embedding`
-- column using the pgvector extension.
--
-- Cosine distance (<=>) is the right metric for normalized embeddings.
-- The bot also exposes /api/faqs/search that does the embed + search +
-- Gemini rephrase in one Express call.
--
-- Non-destructive: CREATE EXTENSION IF NOT EXISTS / CREATE TABLE IF NOT EXISTS.
-- Safe to run on every container start.
-- ============================================================

-- ── pgvector extension ──
-- pgvector ships with the `pgvector/pgvector` Docker image and most managed
-- Postgres providers (Supabase, Neon, RDS). On a vanilla postgres image
-- you need to apt-install postgresql-XX-pgvector first — see docker-compose.yml.
CREATE EXTENSION IF NOT EXISTS vector;

-- ── FAQs ──
CREATE TABLE IF NOT EXISTS faqs (
  id              INTEGER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  question        TEXT          NOT NULL,
  answer          TEXT          NOT NULL,
  category        TEXT,                                            -- e.g. "pricing", "contract", "viewing"
  keywords        TEXT[]        NOT NULL DEFAULT ARRAY[]::TEXT[],   -- admin-managed hints, comma-split input
  sort_order      INTEGER       NOT NULL DEFAULT 100,
  is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
  -- 768 dims matches Gemini text-embedding-004 (outputDimensionality=768).
  -- Nullable so a FAQ can be saved before its first embedding is generated;
  -- the admin UI will then call /api/faqs/:id/regenerate-embedding.
  embedding       vector(768),
  embedding_model TEXT          NOT NULL DEFAULT 'gemini-text-embedding-004',
  embedding_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_faqs_active        ON faqs(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_faqs_category      ON faqs(category) WHERE category IS NOT NULL;
-- HNSW index for fast approximate nearest-neighbour cosine search.
-- HNSW is the recommended pgvector index for read-heavy workloads; for our
-- ~hundreds-of-FAQs scale it's overkill, but it makes the query
-- deterministic < 10ms even if the table grows.
CREATE INDEX IF NOT EXISTS idx_faqs_embedding_hnsw
  ON faqs USING hnsw (embedding vector_cosine_ops)
  WHERE embedding IS NOT NULL;

-- ── auto-update updated_at ──
CREATE OR REPLACE FUNCTION faqs_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_faqs_updated_at ON faqs;
CREATE TRIGGER trg_faqs_updated_at
  BEFORE UPDATE ON faqs
  FOR EACH ROW
  EXECUTE FUNCTION faqs_set_updated_at();